version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DB}
            - POSTGRES_USER=${DB_USER}
        ports:
            - ${DB_PORT}:5432
